### ISSUE TITLE
Battery voltage

### ISSUE THREAD

**Issue by henriAbel** [azerimaker/Penguino-4260#2]
I have been experimenting with reading battery voltage using both Mbed OS and ASF framework but have not been able to get correct results. There seems to be some ADC init error in Mbed OS, I always get 0xFF as voltage. In ASF I was able to get ADC to measure something. Initially I got also max voltage but then i discovered that if i measure with multimeter between JP4 and GND and at the same time look the ADC measurement then voltage seems to be correct. I was able to reproduce same result with previous version of this board. Is there some internal pull-ups that i should disable for PA08 pin?

**Comment by azerimaker** [comment]
Dear @henriAbel, thank you for bringing up this issue. 
To be honest, I've never tried the ADC myself. I suspect this might be due to the selection of the reference voltage.
I would suggest using the [BastWAN sensor example](https://github.com/ElectronicCats/BastWAN/tree/master/Examples/LoRaWAN/lorawan_sensors) with Arduino IDE and see if you're able to get correct readings. There's an example sketch with ADC read function. Whenever I get I chance, I'll also look into that.

**Comment by henriAbel** [comment]
BastWAN sensor example does not use ADC, just generates random values. But i flashed BastWAN Arduino core to the Penguino board and got correct results. So the problem is in my ASF code, have to poke around a litte bit more.
